version: "3.8"
services:
  dev:
    build:
      context: docker/dev
      dockerfile: Dockerfile
      args:
        project_name: $PROJECT_NAME
    container_name: $CONTAINER_NAME
    tty: true
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - 80:3000
    volumes:
      - ./app:/work/app
